version: 1.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2015
install:
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe
before_build:
  - nuget restore couchbase-aspnet-core.sln
build:
  verbosity: minimal
test_script:
  - dotnet test test\Couchbase.Extensions.Caching.UnitTests
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
